/* Generated By:JavaCC: Do not edit this line. testConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface testConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CW = 1;
  /** RegularExpression Id. */
  int C1 = 2;
  /** RegularExpression Id. */
  int C2 = 3;
  /** RegularExpression Id. */
  int FUNCTION = 4;
  /** RegularExpression Id. */
  int NULL = 5;
  /** RegularExpression Id. */
  int OPEN1 = 6;
  /** RegularExpression Id. */
  int BREAK = 7;
  /** RegularExpression Id. */
  int CASE = 8;
  /** RegularExpression Id. */
  int SWITCH = 9;
  /** RegularExpression Id. */
  int FOR = 10;
  /** RegularExpression Id. */
  int DO = 11;
  /** RegularExpression Id. */
  int WHILE = 12;
  /** RegularExpression Id. */
  int NOTEQU = 13;
  /** RegularExpression Id. */
  int END = 14;
  /** RegularExpression Id. */
  int SMALLEQU = 15;
  /** RegularExpression Id. */
  int BIGEQU = 16;
  /** RegularExpression Id. */
  int SMALL = 17;
  /** RegularExpression Id. */
  int DOTS = 18;
  /** RegularExpression Id. */
  int ENDOF = 19;
  /** RegularExpression Id. */
  int OPEN = 20;
  /** RegularExpression Id. */
  int BIG = 21;
  /** RegularExpression Id. */
  int IF = 22;
  /** RegularExpression Id. */
  int QUT = 23;
  /** RegularExpression Id. */
  int STRING = 24;
  /** RegularExpression Id. */
  int EQU = 25;
  /** RegularExpression Id. */
  int EQUEQU = 26;
  /** RegularExpression Id. */
  int INT = 27;
  /** RegularExpression Id. */
  int DOUBLE = 28;
  /** RegularExpression Id. */
  int PLUS = 29;
  /** RegularExpression Id. */
  int MINUS = 30;
  /** RegularExpression Id. */
  int MUL = 31;
  /** RegularExpression Id. */
  int DIV = 32;
  /** RegularExpression Id. */
  int CHAR = 33;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"Console.writeline\"",
    "\"}\"",
    "\")\"",
    "\"function\"",
    "\"null\"",
    "\"(\"",
    "\"break\"",
    "\"case\"",
    "\"switch\"",
    "\"for\"",
    "\"do\"",
    "\"while\"",
    "\"!=\"",
    "\";\"",
    "\"<=\"",
    "\">=\"",
    "\"<\"",
    "\":\"",
    "\"EOF\"",
    "\"{\"",
    "\">\"",
    "\"if\"",
    "\"\\\"\"",
    "\"string\"",
    "\"=\"",
    "\"==\"",
    "\"int\"",
    "<DOUBLE>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "<CHAR>",
    "\",\"",
    "\"++\"",
    "\"--\"",
    "\"+=\"",
    "\"-=\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
  };

}
